// <auto-generated />
namespace CinemaApi.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class GenreFromEnumToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreFromEnumToString));
        
        string IMigrationMetadata.Id
        {
            get { return "202303122134047_GenreFromEnumToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
